kind: Secret
apiVersion: v1
metadata:
  name: test-env-secret 
  namespace: test-cachet
data:
  cachethostnamekey: YW0tY2FjaGV0LmFwcHMudGFjb3N1cHJlbWUub3V0c3JpZ2h0cy5jYw== 
  # cachetusernamekey: 
  # cachetpasswordkey: 
  cachettokenkey: VwnwfJirtBMWOIVWCzvG
  insightsserverkey: Y2xvdWQucmVkaGF0LmNvbQ==
  insightsusernamekey: aW5zaWdodHMtcWE=
  insightspasswordkey: V2VBcmVJbnNpZ2h0c1FFIQ==
  pythonwarningskey: aWdub3JlOlVudmVyaWZpZWQgSFRUUFMgcmVxdWVzdA==
type: Opaque

